### ISSUE TITLE
[FR] Creating modules folder for custom builds

### ISSUE THREAD

**Issue by ajhorvath20** [hotio/caddy#1]
Hi hotio,

Thank you so much for your support. I have two requests if its possible. 

Caddy is working great, can I request if you can create a `modules` folder in the config?

1. Currently I can create a module folder and leave the modules in the there but if this can be done by default. 
2. Also it would be great if caddy can pick up the modules from the folder instead of declaring in environment that way we can just restart the container instead of recreating.

For 1st request I looked at `00-start-container` and if this can be added in there `mkdir "/${CONFIG_DIR}/modules"`

Thank you so much

**Comment by mrhotio** [comment]
imo invalid feature request

**Comment by ajhorvath20** [comment]
Oops shall I change it to support request or something? 

Because its not an issue so I didnt know what to choose. 

Thanks
